# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ContactPlugin_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_contactPluginWidget(object):
    def setupUi(self, contactPluginWidget):
        contactPluginWidget.setObjectName("contactPluginWidget")
        contactPluginWidget.resize(598, 458)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(contactPluginWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(contactPluginWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.groupBox = QtWidgets.QGroupBox(contactPluginWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.contact_val_LB = QtWidgets.QLabel(self.groupBox)
        self.contact_val_LB.setObjectName("contact_val_LB")
        self.verticalLayout_3.addWidget(self.contact_val_LB)
        self.contact_value_LE = QtWidgets.QLineEdit(self.groupBox)
        self.contact_value_LE.setObjectName("contact_value_LE")
        self.verticalLayout_3.addWidget(self.contact_value_LE)
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(contactPluginWidget)
        QtCore.QMetaObject.connectSlotsByName(contactPluginWidget)

    def retranslateUi(self, contactPluginWidget):
        _translate = QtCore.QCoreApplication.translate
        contactPluginWidget.setWindowTitle(_translate("contactPluginWidget", "Form"))
        self.label.setText(_translate("contactPluginWidget", "Contact plugin widget layout"))
        self.groupBox.setTitle(_translate("contactPluginWidget", "Contact widget info:"))
        self.contact_val_LB.setText(_translate("contactPluginWidget", "Contact value:"))
