# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ContactPlugin_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_contactPluginWidget(object):
    def setupUi(self, contactPluginWidget):
        contactPluginWidget.setObjectName("contactPluginWidget")
        contactPluginWidget.resize(400, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(contactPluginWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(contactPluginWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.groupBox = QtWidgets.QGroupBox(contactPluginWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(contactPluginWidget)
        QtCore.QMetaObject.connectSlotsByName(contactPluginWidget)

    def retranslateUi(self, contactPluginWidget):
        _translate = QtCore.QCoreApplication.translate
        contactPluginWidget.setWindowTitle(_translate("contactPluginWidget", "Form"))
        self.label.setText(_translate("contactPluginWidget", "Contact plugin widget layout"))
        self.groupBox.setTitle(_translate("contactPluginWidget", "Contact widget info:"))
