# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtWidgets


class Ui_interactivePlotPage(object):
    def setupUi(self, interactivePlotPage):
        interactivePlotPage.setObjectName("interactivePlotPage")
        interactivePlotPage.resize(900, 620)
        self.mainLayout = QtWidgets.QVBoxLayout(interactivePlotPage)
        self.mainLayout.setContentsMargins(8, 8, 8, 8)
        self.mainLayout.setObjectName("mainLayout")

        self.splitter = QtWidgets.QSplitter(interactivePlotPage)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")

        self.plotListPanel = QtWidgets.QWidget(self.splitter)
        self.plotListLayout = QtWidgets.QVBoxLayout(self.plotListPanel)
        self.plotListLayout.setContentsMargins(0, 0, 8, 0)
        self.plotListLayout.setObjectName("plotListLayout")
        self.plotListLabel = QtWidgets.QLabel(self.plotListPanel)
        self.plotListLabel.setObjectName("plotListLabel")
        self.plotListLayout.addWidget(self.plotListLabel)
        self.plotListWidget = QtWidgets.QListWidget(self.plotListPanel)
        self.plotListWidget.setObjectName("plotListWidget")
        self.plotListLayout.addWidget(self.plotListWidget)
        self.plotButtonsLayout = QtWidgets.QHBoxLayout()
        self.plotButtonsLayout.setObjectName("plotButtonsLayout")
        self.addPlotPB = QtWidgets.QPushButton(self.plotListPanel)
        self.addPlotPB.setObjectName("addPlotPB")
        self.plotButtonsLayout.addWidget(self.addPlotPB)
        self.removePlotPB = QtWidgets.QPushButton(self.plotListPanel)
        self.removePlotPB.setObjectName("removePlotPB")
        self.plotButtonsLayout.addWidget(self.removePlotPB)
        self.plotListLayout.addLayout(self.plotButtonsLayout)

        self.detailsPanel = QtWidgets.QWidget(self.splitter)
        self.detailsLayout = QtWidgets.QVBoxLayout(self.detailsPanel)
        self.detailsLayout.setContentsMargins(8, 0, 0, 0)
        self.detailsLayout.setObjectName("detailsLayout")

        self.plotParamsGB = QtWidgets.QGroupBox(self.detailsPanel)
        self.plotParamsGB.setObjectName("plotParamsGB")
        self.plotParamsLayout = QtWidgets.QGridLayout(self.plotParamsGB)
        self.plotParamsLayout.setObjectName("plotParamsLayout")
        self.titleLabel = QtWidgets.QLabel(self.plotParamsGB)
        self.titleLabel.setObjectName("titleLabel")
        self.plotParamsLayout.addWidget(self.titleLabel, 0, 0, 1, 1)
        self.titleLE = QtWidgets.QLineEdit(self.plotParamsGB)
        self.titleLE.setObjectName("titleLE")
        self.plotParamsLayout.addWidget(self.titleLE, 0, 1, 1, 3)
        self.xAxisLabel = QtWidgets.QLabel(self.plotParamsGB)
        self.xAxisLabel.setObjectName("xAxisLabel")
        self.plotParamsLayout.addWidget(self.xAxisLabel, 1, 0, 1, 1)
        self.xAxisTitleLE = QtWidgets.QLineEdit(self.plotParamsGB)
        self.xAxisTitleLE.setObjectName("xAxisTitleLE")
        self.plotParamsLayout.addWidget(self.xAxisTitleLE, 1, 1, 1, 3)
        self.yAxisLabel = QtWidgets.QLabel(self.plotParamsGB)
        self.yAxisLabel.setObjectName("yAxisLabel")
        self.plotParamsLayout.addWidget(self.yAxisLabel, 2, 0, 1, 1)
        self.yAxisTitleLE = QtWidgets.QLineEdit(self.plotParamsGB)
        self.yAxisTitleLE.setObjectName("yAxisTitleLE")
        self.plotParamsLayout.addWidget(self.yAxisTitleLE, 2, 1, 1, 3)

        self.plotTypeGB = QtWidgets.QGroupBox(self.plotParamsGB)
        self.plotTypeGB.setObjectName("plotTypeGB")
        self.plotTypeLayout = QtWidgets.QHBoxLayout(self.plotTypeGB)
        self.linePlotRB = QtWidgets.QRadioButton(self.plotTypeGB)
        self.linePlotRB.setChecked(True)
        self.linePlotRB.setObjectName("linePlotRB")
        self.plotTypeLayout.addWidget(self.linePlotRB)
        self.histogramPlotRB = QtWidgets.QRadioButton(self.plotTypeGB)
        self.histogramPlotRB.setObjectName("histogramPlotRB")
        self.plotTypeLayout.addWidget(self.histogramPlotRB)
        self.plotParamsLayout.addWidget(self.plotTypeGB, 3, 0, 1, 2)

        self.xLogScaleCB = QtWidgets.QCheckBox(self.plotParamsGB)
        self.xLogScaleCB.setChecked(False)
        self.xLogScaleCB.setObjectName("xLogScaleCB")
        self.plotParamsLayout.addWidget(self.xLogScaleCB, 4, 0, 1, 1)

        self.yLogScaleCB = QtWidgets.QCheckBox(self.plotParamsGB)
        self.yLogScaleCB.setChecked(False)
        self.yLogScaleCB.setObjectName("yLogScaleCB")
        self.plotParamsLayout.addWidget(self.yLogScaleCB, 4, 1, 1, 1)

        self.showLegendCB = QtWidgets.QCheckBox(self.plotParamsGB)
        self.showLegendCB.setChecked(True)
        self.showLegendCB.setObjectName("showLegendCB")
        self.plotParamsLayout.addWidget(self.showLegendCB, 4, 2, 1, 1)
        self.detailsLayout.addWidget(self.plotParamsGB)

        self.seriesGB = QtWidgets.QGroupBox(self.detailsPanel)
        self.seriesGB.setObjectName("seriesGB")
        self.seriesLayout = QtWidgets.QVBoxLayout(self.seriesGB)
        self.seriesControlsLayout = QtWidgets.QHBoxLayout()
        self.xValueLabel = QtWidgets.QLabel(self.seriesGB)
        self.xValueLabel.setObjectName("xValueLabel")
        self.seriesControlsLayout.addWidget(self.xValueLabel)
        self.xValueLE = QtWidgets.QLineEdit(self.seriesGB)
        self.xValueLE.setObjectName("xValueLE")
        self.seriesControlsLayout.addWidget(self.xValueLE)
        self.yValueLabel = QtWidgets.QLabel(self.seriesGB)
        self.yValueLabel.setObjectName("yValueLabel")
        self.seriesControlsLayout.addWidget(self.yValueLabel)
        self.yValueCB = QtWidgets.QComboBox(self.seriesGB)
        self.yValueCB.setObjectName("yValueCB")
        self.seriesControlsLayout.addWidget(self.yValueCB)
        self.addSeriesPB = QtWidgets.QPushButton(self.seriesGB)
        self.addSeriesPB.setObjectName("addSeriesPB")
        self.seriesControlsLayout.addWidget(self.addSeriesPB)
        self.removeSeriesPB = QtWidgets.QPushButton(self.seriesGB)
        self.removeSeriesPB.setObjectName("removeSeriesPB")
        self.seriesControlsLayout.addWidget(self.removeSeriesPB)
        self.seriesLayout.addLayout(self.seriesControlsLayout)
        self.seriesTable = QtWidgets.QTableWidget(self.seriesGB)
        self.seriesTable.setColumnCount(3)
        self.seriesTable.setObjectName("seriesTable")
        self.seriesTable.setHorizontalHeaderLabels(["Series", "X", "Y"])
        self.seriesTable.horizontalHeader().setStretchLastSection(True)
        self.seriesTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.seriesTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.seriesLayout.addWidget(self.seriesTable)
        self.detailsLayout.addWidget(self.seriesGB)

        self.previewGB = QtWidgets.QGroupBox(self.detailsPanel)
        self.previewGB.setObjectName("previewGB")
        self.previewLayout = QtWidgets.QVBoxLayout(self.previewGB)
        self.previewLayout.setObjectName("previewLayout")
        self.detailsLayout.addWidget(self.previewGB, 1)

        self.mainLayout.addWidget(self.splitter)

        self.retranslateUi(interactivePlotPage)
        QtCore.QMetaObject.connectSlotsByName(interactivePlotPage)

    def retranslateUi(self, interactivePlotPage):
        _translate = QtCore.QCoreApplication.translate
        interactivePlotPage.setTitle(_translate("interactivePlotPage", "Interactive Plots"))
        self.plotListLabel.setText(_translate("interactivePlotPage", "Plots"))
        self.addPlotPB.setText(_translate("interactivePlotPage", "Add Plot"))
        self.removePlotPB.setText(_translate("interactivePlotPage", "Remove Plot"))
        self.plotParamsGB.setTitle(_translate("interactivePlotPage", "Plot Parameters"))
        self.titleLabel.setText(_translate("interactivePlotPage", "Title"))
        self.xAxisLabel.setText(_translate("interactivePlotPage", "X axis title"))
        self.yAxisLabel.setText(_translate("interactivePlotPage", "Y axis title"))
        self.plotTypeGB.setTitle(_translate("interactivePlotPage", "Plot type"))
        self.linePlotRB.setText(_translate("interactivePlotPage", "Line"))
        self.histogramPlotRB.setText(_translate("interactivePlotPage", "Histogram"))
        self.xLogScaleCB.setText(_translate("interactivePlotPage", "Log X scale"))
        self.yLogScaleCB.setText(_translate("interactivePlotPage", "Log Y scale"))
        self.showLegendCB.setText(_translate("interactivePlotPage", "Show legend"))
        self.seriesGB.setTitle(_translate("interactivePlotPage", "Data Series"))
        self.xValueLabel.setText(_translate("interactivePlotPage", "X"))
        self.yValueLabel.setText(_translate("interactivePlotPage", "Y"))
        self.addSeriesPB.setText(_translate("interactivePlotPage", "Add Series"))
        self.removeSeriesPB.setText(_translate("interactivePlotPage", "Remove Series"))
        self.previewGB.setTitle(_translate("interactivePlotPage", "Preview"))
