# when building as standalone package uncomment line below and set version and build_number to proper values
# {% set version = "4.3.1" %}
# {% set build_number = "0" %}

{% set versions = load_file_data('versions.yaml', from_recipe_dir=True) %}

{% set version = versions.get('version') %}
{% set build_number = versions.get('build_number',0) %}
{% set numpy_version = versions.get('numpy_version') %}

package:
  name: cc3d-twedit5
  version: {{ version }}

about:
  home: https://compucell3d.org
  license: LGPL
  license_file: ../LICENSE.txt

extra:
  maintainers: T.J. Sego, Maciek Swat

source:
  # url: https://github.com/CompuCell3D/cc3d-twedit5/archive/master.tar.gz
  path: ../

build:
  number: {{ build_number }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python={{ python }}
    - setuptools

  run:
    - python={{ python }}
    # - numpy=1.18 # only when using conda mambabuild
    # - cc3d={{ version }}  # only when using conda mambabuild
    - cc3d-player5={{ version }}
    - chardet
    - pyqtwebkit
    - sphinx
    - pywin32 # [win]

test:
  imports:
    - sys
    - cc3d.twedit5
