{% set data = load_setup_py_data() %}

{% set version = data.get('version') %}
{% set python_version = "3.7" %}


package:
  name: cc3d-twedit5
  version: {{ version }}

about:
  home: https://compucell3d.org
  license: LGPL
  license_file: ../LICENSE.txt

extra:
  maintainers: T.J. Sego, Maciek Swat

source:
  # url: https://github.com/CompuCell3D/cc3d-twedit5/archive/master.tar.gz
  path: ../

build:
  number: 3
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python={{ python_version }}
    - setuptools

  run:
    - python={{ python_version }}
    - cc3d-player5={{ version }}
    - chardet
    - pyqtwebkit # [not osx]
    - sphinx
    - pywin32 # [win]

test:
  imports:
    - sys
    - cc3d.twedit5
