# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contactPlugin_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_contactPluginDlg(object):
    def setupUi(self, contactPluginDlg):
        contactPluginDlg.setObjectName("contactPluginDlg")
        contactPluginDlg.resize(381, 365)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(contactPluginDlg)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.contact_plugin_container = QtWidgets.QFrame(contactPluginDlg)
        self.contact_plugin_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contact_plugin_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contact_plugin_container.setObjectName("contact_plugin_container")
        self.verticalLayout.addWidget(self.contact_plugin_container)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.okPB = QtWidgets.QPushButton(contactPluginDlg)
        self.okPB.setObjectName("okPB")
        self.horizontalLayout_3.addWidget(self.okPB)
        self.cancelPB = QtWidgets.QPushButton(contactPluginDlg)
        self.cancelPB.setObjectName("cancelPB")
        self.horizontalLayout_3.addWidget(self.cancelPB)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(contactPluginDlg)
        self.okPB.clicked.connect(contactPluginDlg.accept) # type: ignore
        self.cancelPB.clicked.connect(contactPluginDlg.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(contactPluginDlg)

    def retranslateUi(self, contactPluginDlg):
        _translate = QtCore.QCoreApplication.translate
        contactPluginDlg.setWindowTitle(_translate("contactPluginDlg", "Please define contact energies"))
        self.okPB.setText(_translate("contactPluginDlg", "OK"))
        self.cancelPB.setText(_translate("contactPluginDlg", "Cancel"))
